name: Build PDFs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pdf_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute the name of the next release
        id: next_tag
        uses: actions/github-script@v7
        with:
          script: |
            // Get the latest release
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });

            // Releases are named "vX", extract X
            const latestTag = releases[0].tag_name;
            const current = parseInt(latestTag.slice(1), 10);

            const tag = `v${current + 1}`;

            // Create a step output for the new version
            core.setOutput('tag', tag);

      - uses: addnab/docker-run-action@v3
        with:
          image: aergus/latex:2025-05-27
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            pdflatex cv_en.tex

      - name: Create the new release an upload the PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.tag }}
          files: cv_en.pdf
          name: ${{ steps.next_tag.outputs.tag }}
          body: "Oh look, a new version!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}